### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PeterMitrano** [WPISmartmouse/smartmouse-simulator#1]
- [ ] compiler that generates C++ from json description of robot (physical and hardware info)
 - [ ] constexpr all the things!
 - [ ] make `maze` support `operator(int, int)`
 - [ ] make const correct
 - [ ] user override in all the command class declarations
 - [ ] [east const!](https://www.youtube.com/watch?v=fovPSk8ixK4)
 - [ ] C++ 17 literals
 - [ ] should digitalWrite use true/false? or uint8_t?
 - [x] rename abstract maze to just maze
 - [ ] ICWYY
 - [x] namespace all the things!
- [x] rename files to be lowercase (match [google style guide](https://google.github.io/styleguide/cppguide.html#File_Names))
- [x] make `#include` statements include some hint at directory structure or which project it belongs too
- [x] Add support for building executables with GCC Sanitizers
